---
version: '3.8'

services:
  web:
    container_name: tdd.io-fastapi
    image: tdd.io-fastapi
    build:
      context: ./
      args:
        - POETRY_VERSION=1.1.12
    entrypoint: /usr/local/bin/uvicorn
    command: app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./project:/usr/src/app
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@web-db:5432/web_dev
    depends_on:
      web-db:
        condition: service_healthy
  web-db:
    container_name: tdd.io-postgres
    image: tdd.io-postgres
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 2s
      timeout: 2s
      retries: 30
